Downgrade connexion ==2.3.0
thoth-station/user-api pull request #1710
Opened 2022-03-09 15:15 UTC by mayaCostantini

## Related Issues and Dependencies

Related to #1708 

## This introduces a breaking change

- No

## This should yield a new module release

- Yes

## This Pull Request implements

Downgrade `connexion` to version `2.3.0` to fix the `ImportError` from `werkzeug`.

2022-03-09 15:15 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **mayacostantini** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fuser-api).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/user-api/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["mayacostantini"]} -->

2022-03-14 05:27 UTC, harshad16 commented
/deploy

2022-03-14 05:58 UTC, harshad16 requested changes
This solution doesnt seems to be working, tested on test cluster
also verified on my own system:
```
hnalla@workstation ~ $ podman run -it quay.io/thoth-station/user-api:pr-1710 bash                                                     
(app-root) python
Python 3.8.8 (default, Aug 11 2021, 06:52:42) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from werkzeug import FileStroage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'FileStroage' from 'werkzeug' (/opt/app-root/lib64/python3.8/site-packages/werkzeug/__init__.py)
>>> 
(app-root) pip show connexion
Name: connexion
Version: 2.3.0
Summary: Connexion - API first applications with OpenAPI/Swagger and Flask
Home-page: https://github.com/zalando/connexion
Author: Zalando SE
Author-email: None
License: Apache License Version 2.0
Location: /opt/app-root/lib/python3.8/site-packages
Requires: clickclick, openapi-spec-validator, jsonschema, requests, PyYAML, six, flask, inflection
Required-by: 
```

2022-03-14 10:55 UTC, mayaCostantini commented
Thanks for the review @harshad16 
I found a combination of dependencies that work locally and added the changes in https://github.com/thoth-station/user-api/pull/1716
Let's close this PR
/close

2022-03-14 10:55 UTC, closed without merging

2022-03-14 10:55 UTC, sesheta commented
@mayaCostantini: Closed this PR.

<details>

In response to [this](https://github.com/thoth-station/user-api/pull/1710#issuecomment-1066640633):

>Thanks for the review @harshad16 
>I found a combination of dependencies that work locally and added the changes in https://github.com/thoth-station/user-api/pull/1716
>Let's close this PR
>/close


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>