[WIP] Add TTL of cached documents in response headers
thoth-station/user-api pull request #1798
Opened 2022-08-23 13:43 UTC by mayaCostantini

## Related Issues and Dependencies

Related to https://github.com/thoth-station/user-api/issues/1614

## This introduces a breaking change

- Yes

## This should yield a new module release

- Yes

## This Pull Request implements

Add TTL for cached documents in HTTP response headers for the following endpoints:

- `/advise/python`
- `/analyze`
- `/build-analysis`
- `/provenance/python`

## Description

This PR is a work in progress: 

- [ ] Needs testing
- [ ] Depends on https://github.com/thoth-station/storages/pull/2676

2022-08-23 13:43 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **mayacostantini** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fuser-api).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/user-api/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["mayacostantini"]} -->

2022-09-02 21:37 UTC, KPostOffice commented on thoth/user_api/api_v1.py
> +                    {"x-thoth-cached-document-ttl": cache_ttl},
Does the third element in the tuple map to headers?

2022-09-13 12:07 UTC, harshad16 requested changes
lgtm
however one of headers is missing.

2022-09-13 12:07 UTC, harshad16 commented on thoth/user_api/api_v1.py
> +        {"x-thoth-cached-document-ttl": cache_ttl},
This is missing from the schema
https://github.com/thoth-station/user-api/blob/1aab302c5cb31064316bb43e7ce8fb5d893d31de/openapi/openapi.yaml#L889

2022-09-14 11:49 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
**Once this PR has been reviewed and has the lgtm label**, please ask for approval from mayacostantini by writing `/assign @mayacostantini` in a comment. For more information see:[The Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fuser-api).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/user-api/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["mayacostantini"]} -->

2023-05-29 09:15 UTC, closed without merging